import Foundation

/// 「現在地を追加」で使う名前の書式を一箇所に集約する。
///
/// 新規登録（LocationsView）と、旧バージョンが生成した時刻入り名前の移行
/// （LocalLocationStore.clarifyCurrentLocationNamesIfNeeded）の両方がここを通ることで、
/// 時刻の書式（"H時mm分"）と「現在地（…に登録）」の組み立てが2箇所で食い違わないようにする。
/// 永続化層（LocalLocationStore）は、この名前がどう組み立てられているかを知らなくてよい。
enum CurrentLocationNaming {

    /// 「現在地を追加」で新規に付ける名前。
    /// - Parameters:
    ///   - date: 登録時刻。
    ///   - timeZone: 時刻表記に使うタイムゾーン。テストから固定できるよう注入可能にする
    ///     （実装は端末のタイムゾーンに追従させたいので既定値は `.current`）。
    static func name(at date: Date, timeZone: TimeZone = .current) -> String {
        name(timeText: timeText(at: date, timeZone: timeZone))
    }

    /// 旧名から取り出した時刻表記を差し込んだ名前（移行用）。
    /// "11:49" のように午前/午後・AM/PM を含まない純粋な時刻表記なら、新規登録と同じ
    /// "H時mm分" 形式に正規化する。"午前11:49"・"3:05 pm" のように解析できない表記は
    /// 無理をせずそのまま差し込む。すでに "H時mm分" 形式の文字列（name(at:) からの入力）を
    /// 渡した場合は正規化の対象にならず（コロン・ピリオド区切りではないため）、そのまま使われる。
    static func name(timeText: String) -> String {
        "現在地（\(normalizedTimeText(timeText))に登録）"
    }

    /// 指定した日時を "H時mm分" 形式の文字列にする（新規登録用）。
    private static func timeText(at date: Date, timeZone: TimeZone) -> String {
        let formatter = DateFormatter()
        formatter.locale = Locale(identifier: "ja_JP")
        formatter.dateFormat = "H時mm分"
        formatter.timeZone = timeZone
        return formatter.string(from: date)
    }

    /// キャプチャした時刻表記が「午前/午後・AM/PM を含まない純粋な時刻」かどうかを見る正規表現。
    /// これに一致する場合だけ "H時mm分" 表記に正規化する（例: "11:49" → "11時49分"）。
    private static let pureTimePattern = try? NSRegularExpression(pattern: "^\\d{1,2}[:.]\\d{2}$")

    /// キャプチャした時刻表記を、可能なら「H時mm分」形式に正規化する。
    /// 解析できない・想定外の区切り文字などの場合は、元の文字列をそのまま返す。
    private static func normalizedTimeText(_ capturedTime: String) -> String {
        guard let pattern = pureTimePattern else { return capturedTime }
        let range = NSRange(capturedTime.startIndex..<capturedTime.endIndex, in: capturedTime)
        guard pattern.firstMatch(in: capturedTime, range: range) != nil else { return capturedTime }

        let parts = capturedTime.components(separatedBy: CharacterSet(charactersIn: ":."))
        guard parts.count == 2, let hour = Int(parts[0]), let minute = Int(parts[1]) else {
            return capturedTime
        }
        return String(format: "%d時%02d分", hour, minute)
    }
}

/// 「現在地を追加」が時刻入りの名前（例: 「現在地 (11:49)」）を生成していた頃の
/// パターンに完全一致する名前だけを検出する正規表現。カッコの中身（時刻表記）を
/// キャプチャグループ1として取り出し、CurrentLocationNaming.name(timeText:) に渡すために使う。
/// ユーザーが編集した名前（例: 「現在地 (自宅)」）を巻き込まないよう、時刻表記の
/// バリエーション（24時間表記・12時間表記・午前/午後表記・区切り文字・大小文字の
/// AM/PM・ピリオド付き a.m./p.m.）を網羅する。完全にすべてのロケールを尽くすものでは
/// ないが、取りこぼしがあっても毎起動で再評価されるため後から拡張できる。
///
/// 半角カッコ `(` `)` への完全一致だけを見ているため、新しい表記（全角カッコを使う
/// 「現在地（11時49分に登録）」）が誤って再マッチすることはない。これにより
/// LocalLocationStore.clarifyCurrentLocationNamesIfNeeded を毎回実行しても
/// 二重に書き換わらない。
///
/// SavedLocation は @MainActor に属さないため、この定数もファイルスコープの
/// nonisolated な定数として持つ。
private let currentLocationTimestampPattern =
    try? NSRegularExpression(
        pattern: "^現在地 \\(((?:午前|午後)?\\s*\\d{1,2}[:.]\\d{2}(?:\\s*[APap]\\.?\\s?[Mm]\\.?)?)\\)$"
    )

extension SavedLocation {
    /// 旧バージョンの「現在地を追加」が自動生成した、時刻入りの名前と完全一致する場合、
    /// カッコの中の時刻表記部分（例: "11:49"、"午前11:49"、"3:05 pm"）を返す。
    /// 一致しなければ nil。「現在地 (自宅)」のようにユーザーが編集した名前を
    /// 対象外にするための判定を兼ねる。
    var autoGeneratedCurrentLocationTimeText: String? {
        guard let pattern = currentLocationTimestampPattern else { return nil }
        let range = NSRange(name.startIndex..<name.endIndex, in: name)
        guard let match = pattern.firstMatch(in: name, range: range),
              match.numberOfRanges >= 2,
              let capturedRange = Range(match.range(at: 1), in: name) else {
            return nil
        }
        return String(name[capturedRange])
    }
}
