import Foundation
import Combine

/// 保存場所を端末ローカルに永続化する観察可能ストア。
/// UserDefaults JSON でシンプルに持つ（数十件想定なので十分高速）。
///
/// 将来的に件数が多くなる、または iCloud 同期が欲しくなった時点で
/// SwiftData / CloudKit に移すパスが残るよう、I/F を Codable ベースに保つ。
@MainActor
final class LocalLocationStore: ObservableObject {

    static let shared = LocalLocationStore()

    @Published private(set) var locations: [SavedLocation] = []

    private let defaults: UserDefaults
    private let storeKey: String
    private let seedFlagKey: String
    private let purgeFlagKey: String
    private let encoder = JSONEncoder()
    private let decoder = JSONDecoder()

    /// - Parameters:
    ///   - seedFlagKey: 旧バージョンの「デモ場所を投入済み」フラグ。もうシードしないので
    ///     読み書きしないが、同じキーを別の意味で再利用して事故らないよう予約として残す。
    ///   - purgeFlagKey: 「デモ場所の削除を実行済み」フラグ。テストで差し替えられるよう注入可能にする。
    init(
        defaults: UserDefaults = .standard,
        storeKey: String = "saved_locations_v1",
        seedFlagKey: String = "has_seeded_demo_locations_v1",
        purgeFlagKey: String = "has_purged_demo_locations_v1"
    ) {
        self.defaults = defaults
        self.storeKey = storeKey
        self.seedFlagKey = seedFlagKey
        self.purgeFlagKey = purgeFlagKey
        self.locations = load()
    }

    // MARK: - CRUD

    func add(name: String, lat: Double, lon: Double, notificationLevel: String? = nil) -> SavedLocation {
        let new = SavedLocation(
            id: UUID().uuidString,
            name: name,
            lat: lat,
            lon: lon,
            notificationLevel: notificationLevel
        )
        locations.append(new)
        save()
        return new
    }

    func delete(id: String) {
        locations.removeAll { $0.id == id }
        save()
    }

    func deleteAll(ids: [String]) {
        let set = Set(ids)
        locations.removeAll { set.contains($0.id) }
        save()
    }

    func update(
        id: String,
        name: String? = nil,
        lat: Double? = nil,
        lon: Double? = nil,
        notificationLevel: String? = nil
    ) -> SavedLocation? {
        guard let idx = locations.firstIndex(where: { $0.id == id }) else { return nil }
        let old = locations[idx]
        let updated = SavedLocation(
            id: old.id,
            name: name ?? old.name,
            lat: lat ?? old.lat,
            lon: lon ?? old.lon,
            notificationLevel: notificationLevel ?? old.notificationLevel
        )
        locations[idx] = updated
        save()
        return updated
    }

    func setNotificationLevel(id: String, level: String) -> SavedLocation? {
        return update(id: id, notificationLevel: level)
    }

    // MARK: - Demo Seed Cleanup

    /// 旧バージョンが初回起動時に投入したデモ場所を、一度だけ削除する。
    /// ユーザーが登録していない土地の危険度や通知を出さないための後始末。
    /// 新規インストールでは消す対象が無いので何も起きない（シードもしない）。
    ///
    /// 名前や座標を編集したデモ地点は、ユーザーが自分の場所として使っている可能性が
    /// あるので残す（isUntouchedDemoSeed の判定）。
    /// 実行済みフラグを立てるので、以降ユーザーが同名・同座標の場所を自分で作っても消えない。
    func purgeDemoSeedsIfNeeded() {
        guard !defaults.bool(forKey: purgeFlagKey) else { return }
        // 何も消さなかった場合でも二度と走らせない（ユーザーの新しい場所を巻き込まないため）。
        defer { defaults.set(true, forKey: purgeFlagKey) }

        let remaining = locations.filter { !$0.isUntouchedDemoSeed }
        // 消すものが無ければ保存もしない（不要な書き込みと @Published 通知を避ける）。
        guard remaining.count != locations.count else { return }
        locations = remaining
        save()
    }

    // MARK: - Current Location Name Clarification

    /// 旧バージョンの「現在地を追加」が生成していた時刻入りの名前（例: 「現在地 (11:49)」）を、
    /// 「何時何分に登録した場所か」がひと目で分かる表記（例: 「現在地（11時49分に登録）」）に
    /// 書き換える。
    ///
    /// 自動生成パターンに完全一致する名前だけを対象にする。「現在地 (自宅)」のようにユーザーが
    /// 編集した名前は対象外（autoGeneratedCurrentLocationTimeText の判定。CurrentLocationNaming.swift
    /// 参照）。カッコの中の時刻表記は捨てず、CurrentLocationNaming.name(timeText:) に渡して
    /// 新規登録と同じ書式で組み立て直す。名前以外のフィールド（id・座標・通知レベル）は変更しない。
    ///
    /// purgeDemoSeedsIfNeeded とは異なり、実行済みフラグを持たず毎回呼ばれるたびに評価する。
    /// デモシードの削除は「ユーザーの場所を消す」破壊的操作なので一度きりが正しいが、
    /// こちらは「名前の正規化」であり、正規表現に取りこぼしがあっても次回の呼び出しで
    /// 自動的に救済されてほしい（フラグで固定すると、その端末だけ永遠に直らなくなる）。
    /// 新しい表記は全角カッコを使うため旧パターンには再マッチせず（CurrentLocationNaming.swift の
    /// currentLocationTimestampPattern のコメント参照）、毎回実行しても二重に「に登録」が付くことはない。
    func clarifyCurrentLocationNamesIfNeeded() {
        var didChange = false
        let clarified: [SavedLocation] = locations.map { location in
            guard let capturedTime = location.autoGeneratedCurrentLocationTimeText else { return location }
            didChange = true
            return SavedLocation(
                id: location.id,
                name: CurrentLocationNaming.name(timeText: capturedTime),
                lat: location.lat,
                lon: location.lon,
                notificationLevel: location.notificationLevel
            )
        }
        guard didChange else { return }
        locations = clarified
        save()
    }

    // MARK: - Persistence

    private func load() -> [SavedLocation] {
        guard let data = defaults.data(forKey: storeKey) else { return [] }
        return (try? decoder.decode([SavedLocation].self, from: data)) ?? []
    }

    private func save() {
        guard let data = try? encoder.encode(locations) else { return }
        defaults.set(data, forKey: storeKey)
    }
}
